
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schoolApp
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
         format_sql: true

  jwt:
   secret: 556A586E3272357538782F413F4428472B4B6250645367566B59703373367639
   jwtExpirationTime: 604800000

server:
  port: 2222





