spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schoolApp
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: 556A586E3272357538782F413F4428472B4B6250645367566B59703373367639
    jwtExpirationTime: 604800000

  mail:
    host: smtp.gmail.com
    port: 587
    username: malakite4malachy@gmail.com
    password: timmzjrnrmtutooy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 2222
